---

- name: Write a file with one set of contents, then another.
  hosts: all

  tasks:

  - name: Template out Version A
    lineinfile:
      path: "{{ one.path }}"
      state: present
      create: yes
      line: "{{ one.contents }}"
      regexp: "^.*version"
    register: a
    no_log: true

  - name: Template out Version B
    lineinfile:
      path: "{{ two.path }}"
      state: present
      create: yes
      line: "{{ two.contents }}"
      regexp: "^.*version"
